version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./:/var/www/html"
            - "./docker/etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "80:80"
        restart: always
        depends_on:
            - php
    php:
        image: nanoninja/php-fpm:latest
        restart: always
        volumes:
            - "./docker/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./:/var/www/html"
